### ISSUE TITLE
Incomplete installation on windows platform

### ISSUE THREAD

**Issue by ivergara** [conda-forge/locust-feedstock#56]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When installing the `locust` package from conda-forge on a windows platform, the execution fails 

```python
❯ locust -v
Traceback (most recent call last):
  File "C:\Users\iverg\miniconda3\envs\janus\Scripts\locust-script.py", line 5, in <module>
    from locust.main import main
  File "C:\Users\iverg\miniconda3\envs\janus\lib\site-packages\locust\main.py", line 27, in <module>
    from .input_events import input_listener
  File "C:\Users\iverg\miniconda3\envs\janus\lib\site-packages\locust\input_events.py", line 9, in <module>
    from win32api import STD_INPUT_HANDLE
ModuleNotFoundError: No module named 'win32api'
```

Installing the package `pywin32` fixed the issue. The `setup.py` file in locust's repository states such package is needed for windows platforms, but this recipe is not considering that.

### Installed packages

```shell
# Name                    Version                   Build  Channel
anyio                     3.5.0           py310h5588dad_0    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     22.1.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.0.9           py310h8a704f9_6    conda-forge
brotlipy                  0.7.0           py310he2412df_1003    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8       py310h5588dad_1    conda-forge
cffi                      1.15.0          py310hcbf9ad4_0    conda-forge
chardet                   4.0.0           py310h5588dad_2    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.0.4           py310h5588dad_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
configargparse            1.5.3              pyhd8ed1ab_0    conda-forge
cookiecutter              1.7.3              pyh6c4a22f_1    conda-forge
cryptography              36.0.0          py310h21b164f_0
dataclasses               0.8                pyhc8e2a94_3    conda-forge
exrex                     0.10.5                   pypi_0    pypi
faker                     13.3.0                   pypi_0    pypi
flask                     2.0.3              pyhd8ed1ab_0    conda-forge
flask-basicauth           0.2.0              pyh9f0ad1d_3    conda-forge
flask-cors                3.0.10             pyhd8ed1ab_0    conda-forge
flask-pydantic-spec       0.3.0                    pypi_0    pypi
future                    0.18.2          py310h5588dad_4    conda-forge
gevent                    21.12.0         py310he2412df_0    conda-forge
geventhttpclient          1.5.3           py310he2412df_2    conda-forge
greenlet                  1.1.2           py310h8a704f9_1    conda-forge
h11                       0.12.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  0.14.7             pyhd8ed1ab_0    conda-forge
httpx                     0.22.0          py310h5588dad_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
hypothesis                6.39.0             pyhd8ed1ab_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
inflection                0.5.1                    pypi_0    pypi
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.0              pyhd8ed1ab_0    conda-forge
janus                     0.0.0                     dev_0    <develop>
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
locust                    2.8.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.0           py310he2412df_0    conda-forge
msgpack-python            1.0.3           py310h476a331_0    conda-forge
mypy_extensions           0.4.3           py310h5588dad_4    conda-forge
nested-lookup             0.2.23                   pypi_0    pypi
openssl                   3.0.0                h8ffe710_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0           py310h5588dad_2    conda-forge
poyo                      0.5.0                      py_0    conda-forge
psutil                    5.9.0           py310he2412df_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.9.0           py310he2412df_0    conda-forge
pydantic-factories        1.2.5                    pypi_0    pypi
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1           py310h5588dad_4    conda-forge
pytest                    7.0.1           py310h5588dad_0    conda-forge
python                    3.10.2          hcf16a7b_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-slugify            6.1.1              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pyzmq                     22.3.0          py310h73ada01_1    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
respx                     0.19.2             pyhd8ed1ab_0    conda-forge
rfc3986                   1.5.0              pyhd8ed1ab_0    conda-forge
rich                      11.2.0             pyhd8ed1ab_0    conda-forge
roundrobin                0.0.2              pyhd8ed1ab_0    conda-forge
setuptools                60.9.3          py310h5588dad_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.2.0           py310h5588dad_2    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.2           py310he2412df_0    conda-forge
typing-extensions         4.1.1                hd8ed1ab_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unidecode                 1.3.3              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
werkzeug                  2.0.3              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0           py310h5588dad_3    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zope.event                4.5.0              pyh9f0ad1d_0    conda-forge
zope.interface            5.4.0           py310he2412df_1    conda-forge
```

### Environment info

```shell
active environment : janus
    active env location : C:\Users\iverg\miniconda3\envs\janus
            shell level : 2
       user config file : C:\Users\iverg\.condarc
 populated config files : C:\Users\iverg\.condarc
          conda version : 4.11.0
    conda-build version : 3.21.4
         python version : 3.8.3.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\iverg\miniconda3  (writable)
      conda av data dir : C:\Users\iverg\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\iverg\miniconda3\pkgs
                          C:\Users\iverg\.conda\pkgs
                          C:\Users\iverg\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\iverg\miniconda3\envs
                          C:\Users\iverg\.conda\envs
                          C:\Users\iverg\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by bollwyvl** [comment]
Good to know. Running locust on windows vs something _on_ windows is... relevant for comparing two versions on the same machine, I guess.

As such: I'm _not_ particularly interested in supporting `n x m` builds of this package, so will try to get some solution to https://github.com/conda-forge/pywin32-feedstock/issues/34 so we can depend on it here.

**Comment by ivergara** [comment]
I'm not exactly sure, but maybe adding to the runtime dependencies the line `- pywin32 # [win]` would be enough?

**Comment by bollwyvl** [comment]
Right, but that would require dropping `noarch: python`. After re-rendering, there would be somewhere in the neighborhood of:

(py3.7, py3.8, py3.9, py3.10, pypy37) x (osx-64, win-64, osx-arm64, linux-64, ppcle, aarch64) builds
